# Generated by Django 4.1.2 on 2022-11-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='firstname',
        ),
    ]
