# Generated by Django 4.1.2 on 2022-11-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_alter_profile_prof_pic_alter_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.profile'),
        ),
    ]
