# Generated by Django 4.1.2 on 2023-10-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0008_rename_categories_category_rename_tags_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-responded_on']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='active',
        ),
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum_app.answer'),
        ),
    ]
