# Generated by Django 4.1.2 on 2023-10-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0010_answer_content_type_answer_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='object_id',
        ),
    ]
