# Generated by Django 4.1.2 on 2023-10-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0011_remove_answer_content_type_remove_answer_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
